[package]
name = "spelling"
version = "0.1.0"
authors = ["frogtd <31412003+frogtd@users.noreply.github.com>"]
edition = "2018"
license = "UNLICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"

[profile.release]
debug = true

[[bin]]
name = "test"
path = "src/test_bin.rs"